name: Maven Package

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      jar_version: ${{ steps.bump.outputs.jar_version }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Compile
      run: mvn -B compile --file ./pom.xml

    - name: Build a package
      run: mvn -B package -DskipTests --file ./pom.xml

    - name: Temporarily save jar artifact
      uses: actions/upload-artifact@v2
      with:
        name: jar-artifact
        path: ${{ github.workspace }}/target/*.jar
        retention-days: 1

  deploy:
    runs-on: ubuntu-18.04
    needs: build

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
          name: jar-artifact
          path: ${{ github.workspace }}/target/
    - name: Docker build
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/souhe:2.0 .
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker push
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/souhe:2.0
  run:
    runs-on: ubuntu-18.04
    needs: [build, deploy]

    steps:
    - name: Run container
      run: |
        docker run ${{ secrets.DOCKER_USERNAME }}/souhe:2.0
